server {
    listen 80 default_server;
    listen [::]:80 default_server;
    
    server_name _;
    root /var/www/html;
    index index.html;

    # Compressione Gzip per prestazioni ottimali
    gzip on;
    gzip_vary on;
    gzip_min_length 1024;
    gzip_proxied expired no-cache no-store private auth;
    gzip_types text/plain text/css text/xml text/javascript application/x-javascript application/xml application/json;

    # Gestione delle rotte per Single Page Application (SPA)
    location / {
        try_files $uri $uri/ /index.html;
    }

    # Caching risorse statiche ed asset di produzione
    location ~* \.(?:css|js|map|jpe?g|png|gif|ico|cur|heic|webp|tiff?|mp4|webm|svg|svgz|ttf|otf|woff|woff2)$ {
        expires 1y;
        add_header Cache-Control "public, no-transform";
    }

    # Disabilita il caching per il file manifest e lo service worker PWA
    location ~* (sw\.js|manifest\.webmanifest)$ {
        expires -1;
        add_header Cache-Control "no-store, no-cache, must-revalidate, proxy-revalidate, max-age=0";
    }
}
